apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
    name: openebs-mystorageclass
provisioner: openebs.io/provisioner-iscsi
parameters:
    openebs.io/jiva-replica-count: "3"
    openebs.io/capacity: "3G"
    openebs.io/jiva-replica-image: "openebs/jiva:0.6.0"
    openebs.io/jiva-controller-image: "openebs/jiva:0.6.0"
    openebs.io/storage-pool: "sp-mntdir"
