apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
    name: openebs-mystorageclass
provisioner: openebs.io/provisioner-iscsi
parameters:
    openebs.io/jiva-replica-count: "1"
    openebs.io/capacity: "1G"
    openebs.io/jiva-replica-image: "openebs/jiva:0.6.0"
